2018-01-30 19:09:44,129:DEBUG:Successfully loaded logging_config.py on pyDBLogger!
1517370138.529781 : 2018-01-30 19:42:18,529 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370138.530186 : 2018-01-30 19:42:18,530 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = ./log/pyDBLogger.db [18]
1517370138.530275 : 2018-01-30 19:42:18,530 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370138.530340 : 2018-01-30 19:42:18,530 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370158.505713 : 2018-01-30 19:42:38,505 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370158.505886 : 2018-01-30 19:42:38,505 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = ./log/pyDBLogger.db [18]
1517370158.505957 : 2018-01-30 19:42:38,505 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370158.506046 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370158.506130 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_to_db = True [18]
1517370158.506192 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if database exists. [18]
1517370158.506279 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:No SQLite3 logging database! Creating one... [18]
1517370260.419540 : 2018-01-30 19:44:20,419 : 1 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370260.420231 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = logs/pyDBLogger.db [18]
1517370260.420404 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370260.420512 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370260.420605 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_to_db = True [18]
1517370260.420708 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if database exists. [18]
1517370260.420871 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:No SQLite3 logging database! Creating one... [18]
1517370260.443669 : 2018-01-30 19:44:20,443 : 25 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Logging database exists! Connecting to database... [18]
1517370260.444597 : 2018-01-30 19:44:20,444 : 26 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully connected to the logging database! [18]
1517370407.542099 : 2018-01-30 19:46:47,542 : 1 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370407.542535 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = logs/pyDBLogger.db [18]
1517370407.542649 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370407.542748 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370407.542860 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_to_db = True [18]
1517370407.542942 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if database exists. [18]
1517370407.543053 : 2018-01-30 19:46:47,543 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Logging database exists! Connecting to database... [18]
1517370407.545480 : 2018-01-30 19:46:47,545 : 5 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully connected to the logging database!... Starting to log to database. [18]
1517371642.573873 : 2018-01-30 20:07:22,573 : 3 | 17060 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517371678.652551 : 2018-01-30 20:07:58,652 : 1 | 17067 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517371678.652696 : 2018-01-30 20:07:58,652 : 1 | 17067 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374068.258565 : 2018-01-30 20:47:48,258 : 1 | 17259 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374068.259268 : 2018-01-30 20:47:48,259 : 2 | 17259 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374728.028509 : 2018-01-30 20:58:48,028 : 1 | 17347 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374728.029154 : 2018-01-30 20:58:48,029 : 2 | 17347 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374904.614653 : 2018-01-30 21:01:44,614 : 1 | 17369 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374904.615361 : 2018-01-30 21:01:44,615 : 2 | 17369 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374923.882692 : 2018-01-30 21:02:03,882 : 1 | 17372 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374923.883025 : 2018-01-30 21:02:03,883 : 1 | 17372 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374943.747226 : 2018-01-30 21:02:23,747 : 1 | 17376 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374943.747420 : 2018-01-30 21:02:23,747 : 1 | 17376 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374958.582097 : 2018-01-30 21:02:38,582 : 1 | 17378 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374958.582304 : 2018-01-30 21:02:38,582 : 1 | 17378 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374964.387181 : 2018-01-30 21:02:44,387 : 0 | 17382 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374964.387324 : 2018-01-30 21:02:44,387 : 0 | 17382 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517374970.319650 : 2018-01-30 21:02:50,319 : 0 | 17385 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517374970.319794 : 2018-01-30 21:02:50,319 : 0 | 17385 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375004.455320 : 2018-01-30 21:03:24,455 : 1 | 17388 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517375004.455467 : 2018-01-30 21:03:24,455 : 1 | 17388 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375088.275738 : 2018-01-30 21:04:48,275 : 1 | 17392 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517375088.276104 : 2018-01-30 21:04:48,276 : 1 | 17392 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375088.276204 : 2018-01-30 21:04:48,276 : 1 | 17392 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Starting pyDBLoader test load [18]
1517375102.227780 : 2018-01-30 21:05:02,227 : 0 | 17395 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517375102.227934 : 2018-01-30 21:05:02,227 : 0 | 17395 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375102.228028 : 2018-01-30 21:05:02,228 : 1 | 17395 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Starting pyDBLoader test load [18]
1517375204.681882 : 2018-01-30 21:06:44,681 : 1 | 17404 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517375204.682560 : 2018-01-30 21:06:44,682 : 2 | 17404 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375204.682775 : 2018-01-30 21:06:44,682 : 2 | 17404 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Starting pyDBLoader test load [18]
1517375204.682926 : 2018-01-30 21:06:44,682 : 2 | 17404 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if config/logger_config.ini is a file: True [18]
1517375218.203275 : 2018-01-30 21:06:58,203 : 1 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517375218.204028 : 2018-01-30 21:06:58,204 : 2 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375218.204370 : 2018-01-30 21:06:58,204 : 2 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Starting pyDBLoader test load [18]
1517375218.204625 : 2018-01-30 21:06:58,204 : 2 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if config/logger_config.ini is a file: True [18]
1517375218.204800 : 2018-01-30 21:06:58,204 : 3 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Verified configuration file: config/logger_config.ini [18]
1517375218.204908 : 2018-01-30 21:06:58,204 : 3 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading configuration file. [18]
1517375218.204996 : 2018-01-30 21:06:58,204 : 3 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if config/logger_config.ini is a file: True [18]
1517375218.207087 : 2018-01-30 21:06:58,207 : 5 | 17410 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Could not load configuration files. Using defaults. [18]
1517375633.503746 : 2018-01-30 21:13:53,503 : 1 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517375633.504501 : 2018-01-30 21:13:53,504 : 2 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375633.504730 : 2018-01-30 21:13:53,504 : 2 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Starting pyDBLoader test load [18]
1517375633.504890 : 2018-01-30 21:13:53,504 : 2 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if config/logger_config.ini is a file: True [18]
1517375633.505016 : 2018-01-30 21:13:53,505 : 2 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Verified configuration file: config/logger_config.ini [18]
1517375633.505119 : 2018-01-30 21:13:53,505 : 2 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading configuration file. [18]
1517375633.505227 : 2018-01-30 21:13:53,505 : 3 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if config/logger_config.ini is a file: True [18]
1517375633.507109 : 2018-01-30 21:13:53,507 : 4 | 17477 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Could not load configuration files. Using defaults. [18]
1517375712.438048 : 2018-01-30 21:15:12,438 : 1 | 17479 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517375712.438309 : 2018-01-30 21:15:12,438 : 1 | 17479 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
1517375712.438546 : 2018-01-30 21:15:12,438 : 1 | 17479 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Starting pyDBLoader test load [18]
1517375712.438750 : 2018-01-30 21:15:12,438 : 2 | 17479 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if ../config/logger_config.ini is a file: False [18]
1517375712.438866 : 2018-01-30 21:15:12,438 : 2 | 17479 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Could not verify configuration file. Using defaults. [18]
1517768243.463050 : 2018-02-04 10:17:23,463 : 0 | 3042 - MainProcess - 140735950283584 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/modules/logging_config.py - logging_config.py - log [42]:[DEBUG/10]:Logging is set up!
1517768243.463435 : 2018-02-04 10:17:23,463 : 1 | 3042 - MainProcess - 140735950283584 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/modules/logging_config.py - logging_config.py - log [42]:[DEBUG/10]:Loading up pyDBLoader...
