2018-01-30 19:09:44,129:DEBUG:Successfully loaded logging_config.py on pyDBLogger!
1517370138.529781 : 2018-01-30 19:42:18,529 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370138.530186 : 2018-01-30 19:42:18,530 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = ./log/pyDBLogger.db [18]
1517370138.530275 : 2018-01-30 19:42:18,530 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370138.530340 : 2018-01-30 19:42:18,530 : 4 | 16976 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370158.505713 : 2018-01-30 19:42:38,505 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370158.505886 : 2018-01-30 19:42:38,505 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = ./log/pyDBLogger.db [18]
1517370158.505957 : 2018-01-30 19:42:38,505 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370158.506046 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370158.506130 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_to_db = True [18]
1517370158.506192 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if database exists. [18]
1517370158.506279 : 2018-01-30 19:42:38,506 : 1 | 16979 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:No SQLite3 logging database! Creating one... [18]
1517370260.419540 : 2018-01-30 19:44:20,419 : 1 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370260.420231 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = logs/pyDBLogger.db [18]
1517370260.420404 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370260.420512 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370260.420605 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_to_db = True [18]
1517370260.420708 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if database exists. [18]
1517370260.420871 : 2018-01-30 19:44:20,420 : 2 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:No SQLite3 logging database! Creating one... [18]
1517370260.443669 : 2018-01-30 19:44:20,443 : 25 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Logging database exists! Connecting to database... [18]
1517370260.444597 : 2018-01-30 19:44:20,444 : 26 | 16988 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully connected to the logging database! [18]
1517370407.542099 : 2018-01-30 19:46:47,542 : 1 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517370407.542535 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:db_path = logs/pyDBLogger.db [18]
1517370407.542649 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_file_path = /var/log/pydbloader.log [18]
1517370407.542748 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_error_level = DEBUG [18]
1517370407.542860 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:log_to_db = True [18]
1517370407.542942 : 2018-01-30 19:46:47,542 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Checking if database exists. [18]
1517370407.543053 : 2018-01-30 19:46:47,543 : 2 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Logging database exists! Connecting to database... [18]
1517370407.545480 : 2018-01-30 19:46:47,545 : 5 | 16998 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully connected to the logging database!... Starting to log to database. [18]
1517371642.573873 : 2018-01-30 20:07:22,573 : 3 | 17060 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517371678.652551 : 2018-01-30 20:07:58,652 : 1 | 17067 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Successfully loaded logging_config.py on pyDBLogger! [18]
1517371678.652696 : 2018-01-30 20:07:58,652 : 1 | 17067 - MainProcess - 140736135070528 - MainThread | /Users/remillardj/Tech/Repo/pyDBLoader/module/pyDBLogger.py - pyDBLogger.py - log:[DEBUG/10]:Loading up pyDBLoader... [18]
